name: Build and Push Image

on:
  push:
    branches: ['main', 'master']
    tags: ['v*']
  pull_request:
    branches: ['main', 'master']
  workflow_dispatch:

jobs:
  build-image:
    uses: x-k-io/.github/.github/workflows/java-service-build-image.yml@main
    with:
      image_name: ${{ github.repository }}
      context_path: '.'